version: "3.7"

services: 
  database: 
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    restart: always

  app:
    build: .
    container_name: rentalx
    ports: 
      - 3030:3030
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on: 
      - database
    restart: always

volumes: 
  pgdata:
    driver: local
